### ISSUE TITLE
Create the form fields

### ISSUE THREAD

**Issue by brendanmcgivern** [brendanmcgivern/formit#9]
a form field - `belongs_to :form`
a form field - `has_many :entries`
a form `belongs_to :user`

a user should be able to add any of the available form fields to their form (text, radio, dropdown)

![screen shot 2015-07-13 at 6 23 00 pm](https://cloud.githubusercontent.com/assets/3156857/8662310/557c56b8-298c-11e5-9ffd-f7bfdbc7e5ae.png)

![screen shot 2015-07-13 at 6 23 31 pm](https://cloud.githubusercontent.com/assets/3156857/8662315/5b882ec4-298c-11e5-89f8-bd58952b3e77.png)

![screen shot 2015-07-13 at 7 06 21 pm](https://cloud.githubusercontent.com/assets/3156857/8662864/55650c32-2992-11e5-878d-c509440a04dc.png)

**Comment by droberts84** [comment]
Did you decide you are using Entry Attribute Value instead of JSON?

**Comment by brendanmcgivern** [comment]
Yes I decided to use Entry Attribute Value instead of JSON.  I like how the JSON method would allow me to have a table of user submissions with one record per user submission, but I feel like I have a better understanding of how Entry Attribute Value will be set up.

**Comment by droberts84** [comment]
I'm happy to explain to you how to use it with JSON.  It is actually a
simpler model, although some data queries might require special syntax.
Basically thinking back to the model I showed you, your submission model
would have an attribute called "data" or whatever you want to call it which
contains JSON of all the responses.  Example for a simple form with name
and address

    Submission id: 1, created_at: '07/13/2015', form_id: 1, data: {name:
'David', address: '123 Easy St'}

Either is fine.. but I want to make sure you understand what would be
involved with both.

**Comment by brendanmcgivern** [comment]
Closing as this is covered by #7
